### ISSUE TITLE
refreshToken tag in oAuth causing issue

### ISSUE THREAD

**Issue by nishanpatel** [jamesward/metadata-merger#1]
Hi James,

I am trying to run this application but in ForceUtil line no.74 "refreshToken" causing an issue. Once app return oAuth response I don't see any "refreshToken" tag in JSON response. 

Please can you guide me is it valid parsing of oAuth response?

**Comment by jamesward** [comment]
The docs definitely indicate that you should be getting a refresh token:
https://www.salesforce.com/us/developer/docs/api_rest/Content/intro_understanding_web_server_oauth_flow.htm

I'm not sure why you wouldn't be getting one.  Is the rest of the info there?

**Comment by nishanpatel** [comment]
Hi James,

I will send you response later, but when I commented refreshToken tag I was successfully able to login into app. 

If I don't comment the json parsing logic at line no.74 throwing an exception and returning none as response and later it shows as unauthorized exception. 

Thanks Jason for reply.

**Comment by jamesward** [comment]
You can do a `println(response.json)` to get the actual response in your console.

**Comment by nishanpatel** [comment]
Hi James,

Previously I have configured at salesforce side in "Selected OAuth Scopes = Full access (full)" only. Once I have added all access in "Selected OAuth Scopes" I was getting refresh_token tag in my repose.

Thanks James

**Comment by jamesward** [comment]
Ah. Good to know.  Thanks.
